on: [push, pull_request]
name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up c++
      uses: actions/setup-cxx@v2
      with:
        cpp-version: '20'


    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libboost-all-dev libpqxx-dev

    - name: Build and test
      run: |
        make
        ./bin/test_server
