on: [push, pull_request]
name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libboost-all-dev libpqxx-dev

    - name: Build and test
      run: |
        make -j
        result=$(./bin/test_server | tee /dev/tty | tail -n 1)
        tests_failed=$(echo "$result" | rev | cut -d' ' -f1 | rev)
        if [ "$tests_failed" -ne 0 ]; then
          exit 1
        fi